### ISSUE TITLE
2 tests are failing on grunt execution

### ISSUE THREAD

**Issue by evgeniy-tg** [sailrish/shipit#34]
1) DHL Global Mail client integration tests in transit package has 5 activities with timestamp, location and details:

      actual expected

      "2014-03-27T0827T15:00:00.000Z"

    at Assertion.assertEqual (C:\git\shipit\node_modules\chai\lib\chai\core\assertions.js:393:19)
    at Assertion.ctx.(anonymous function) [as equal] (C:\git\shipit\node_modules\chai\lib\chai\utils\addMethod.js:40:25)
    at verifyActivity (C:\git\shipit\test\dhlgm.coffee:29:39)
    at Context.<anonymous> (C:\git\shipit\test\dhlgm.coffee:47:9)
    at Test.Runnable.run (C:\git\shipit\node_modules\grunt-mocha-test\node_modules\mocha\lib\runnable.js:211:32)
    at Runner.runTest (C:\git\shipit\node_modules\grunt-mocha-test\node_modules\mocha\lib\runner.js:355:10)
    at C:\git\shipit\node_modules\grunt-mocha-test\node_modules\mocha\lib\runner.js:401:12
    at next (C:\git\shipit\node_modules\grunt-mocha-test\node_modules\mocha\lib\runner.js:281:14)
    at C:\git\shipit\node_modules\grunt-mocha-test\node_modules\mocha\lib\runner.js:290:7
    at next (C:\git\shipit\node_modules\grunt-mocha-test\node_modules\mocha\lib\runner.js:234:23)
    at Immediate.<anonymous> (C:\git\shipit\node_modules\grunt-mocha-test\node_modules\mocha\lib\runner.js:258:5)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
  

  2) ups client validateResponse returns an error if xml response contains no nodes:
     TypeError: Cannot read property 'should' of null
    at C:\git\shipit\test\ups.coffee:108:12
    at handleResponse (C:\git\shipit\lib\ups.js:65:18)
    at Parser.<anonymous> (C:\git\shipit\node_modules\xml2js\lib\parser.js:303:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Object.onend (C:\git\shipit\node_modules\xml2js\lib\parser.js:130:26)
    at emit (C:\git\shipit\node_modules\sax\lib\sax.js:624:35)
    at end (C:\git\shipit\node_modules\sax\lib\sax.js:667:5)
    at Object.write (C:\git\shipit\node_modules\sax\lib\sax.js:975:14)
    at Object.close (C:\git\shipit\node_modules\sax\lib\sax.js:157:38)
    at Parser.exports.Parser.Parser.parseString (C:\git\shipit\node_modules\xml2js\lib\parser.js:322:42)
    at Parser.parseString (C:\git\shipit\node_modules\xml2js\lib\parser.js:5:59)
    at UpsClient.validateResponse (C:\git\shipit\lib\ups.js:84:26)
    at Context.<anonymous> (C:\git\shipit\test\ups.coffee:107:18)
    at Test.Runnable.run (C:\git\shipit\node_modules\grunt-mocha-test\node_modules\mocha\lib\runnable.js:194:15)
    at Runner.runTest (C:\git\shipit\node_modules\grunt-mocha-test\node_modules\mocha\lib\runner.js:355:10)
    at C:\git\shipit\node_modules\grunt-mocha-test\node_modules\mocha\lib\runner.js:401:12
    at next (C:\git\shipit\node_modules\grunt-mocha-test\node_modules\mocha\lib\runner.js:281:14)
    at C:\git\shipit\node_modules\grunt-mocha-test\node_modules\mocha\lib\runner.js:290:7
    at next (C:\git\shipit\node_modules\grunt-mocha-test\node_modules\mocha\lib\runner.js:234:23)
    at Immediate.<anonymous> (C:\git\shipit\node_modules\grunt-mocha-test\node_modules\mocha\lib\runner.js:258:5)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by sailrish** [comment]
now fixed.
